- name: Restart freshrss
  ansible.builtin.systemd_service:
    name: freshrss
    state: restarted

- name: Restart caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted

- name: Restart freshrss-update
  ansible.builtin.systemd_service:
    name: freshrss-update.timer
    state: restarted
    daemon_reload: true
