[package]
name = "selfhost"
version = "0.1.0"
edition = "2024"

[dependencies]
ansible-rs = "1.1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
eyre = "0.6"
color-eyre = "0.6"
dialoguer = "0.11"
skim = "0.10"
dirs = "6"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
namecheap = "0.1"

[dev-dependencies]
tempfile = "3"
