- name: Restart colporteur
  ansible.builtin.systemd_service:
    name: colporteur.timer
    state: restarted
    daemon_reload: true

- name: Restart caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
