- name: SSH Daemon Configuration
  block:
    - name: Install OpenSSH server
      ansible.builtin.apt:
        name: openssh-server
        state: present

    - name: Add new user's SSH public key
      ansible.posix.authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ lookup('file', ssh_public_key_path) }}"

    - name: Use custom sshd_config
      ansible.builtin.template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: "0600"
        validate: "/usr/sbin/sshd -t -f %s"
      notify: Restart sshd
