baikal_install_dir: /opt/baikal
baikal_data_dir: "{{ baikal_install_dir }}/Specific"
baikal_domain: "{{ baikal_subdomain }}.{{ primary_domain }}"
baikal_sys_user: baikal
baikal_fpm_socket: /var/run/php/baikal-fpm.sock
