---
- name: Deploy FreshRSS
  hosts: vpn_server
  become: true
  roles:
    - role: freshrss
      vars:
        freshrss_domain: rss.example.com
        freshrss_port: 8084
        freshrss_version: edge
