booklore_install_path: /opt/booklore
booklore_data_path: /srv/booklore
booklore_bookdrop_path: /srv/bookdrop
booklore_sys_user: booklore
booklore_sys_group: booklore
booklore_port: 6060
booklore_domain: "{{ booklore_subdomain }}.{{ primary_domain }}"

booklore_db_host: localhost
booklore_db_name: booklore
booklore_db_user: booklore

booklore_github_repo: booklore-app/booklore
booklore_version: "2.0.1"
booklore_jar_url: "https://github.com/sripwoud/auberge/releases/download/booklore/v{{ booklore_version }}/booklore-api.jar"
booklore_jvm_opts: "-Xmx768m -XX:+UseG1GC -XX:+UseStringDeduplication"
