yourls_install_path: /var/www/yourls
yourls_sys_user: www-data
yourls_sys_group: www-data
yourls_domain: "{{ yourls_subdomain }}.{{ primary_domain }}"
yourls_version: "1.10.2"

yourls_db_name: yourls
yourls_db_user: yourls
yourls_db_host: localhost
yourls_db_prefix: "yourls_"

yourls_site_title: "URL Shortener"
