- name: Restart php-fpm
  when: yourls_php_fpm_version is defined
  ansible.builtin.systemd_service:
    name: "php{{ yourls_php_fpm_version }}-fpm"
    state: restarted

- name: Restart caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
