ssh_public_key_path: "{{ lookup('env', 'HOME') }}/.ssh/identities/{{ user_name }}_{{ inventory_hostname }}.pub"
ssh_max_auth_tries: 3
ssh_max_sessions: 5
ssh_login_grace_time: 30
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_log_level: "VERBOSE"
ssh_banner_content: |
  ********************************************************************
  *                       AUTHORIZED ACCESS ONLY                     *
  * Unauthorized access to this system is forbidden and will be     *
  * prosecuted by law. By accessing this system, you agree that     *
  * your actions may be monitored and recorded.                     *
  ********************************************************************
