---
- name: Deploy self-hosted applications
  hosts: vps
  become: true
  roles:
    - role: blocky
      tags: [blocky]
    - role: calibre
      tags: [calibre]
    - role: freshrss
      tags: [freshrss]
    - role: navidrome
      tags: [navidrome]
    - role: radicale
      tags: [radicale]
    - role: webdav
      tags: [webdav]
    - role: wireguard
      tags: [wireguard]
    - role: yourls
      tags: [yourls]
