navidrome_sys_user: navidrome
navidrome_sys_group: navidrome
navidrome_port: 4533
navidrome_domain: music.sripwoud.xyz
navidrome_music_folder: /srv/music
navidrome_log_level: info
navidrome_scanner_interval: 24h
navidrome_enable_transcoding: true
navidrome_enable_downloads: true
navidrome_enable_sharing: true

navidrome_github_repo: navidrome/navidrome
navidrome_github_api_latest_release_url: "https://api.github.com/repos/{{ navidrome_github_repo }}/releases/latest"
