---
ansible_user_ssh_public_key_file: "{{ lookup('env', 'HOME') }}/.ssh/identities/ansible_{{ inventory_hostname }}.pub"
ansible_user_admin_name: "{{ admin_user_name }}"
ansible_user_admin_ssh_public_key_file: "{{ lookup('env', 'HOME') }}/.ssh/identities/{{ admin_user_name }}_{{ inventory_hostname }}.pub"
ansible_user_shell: /bin/bash
ansible_user_admin_shell: /bin/bash
