- name: Restart php-fpm
  when: baikal_php_version is defined
  ansible.builtin.systemd_service:
    name: php{{ baikal_php_version }}-fpm
    state: restarted

- name: Restart caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
