name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm -fr .mise/config.toml
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            "check-format" = { run = "dprint check --excludes mise.toml" }
            "check-lint" = { run = "ansible-lint", dir = "ansible" }
            "check" = { depends = "check-*" }
            [tools]
            dprint = "latest"
            pipx = "latest"
            "pipx:ansible-core" = "latest"
            "pipx:ansible-lint" = "latest"
      - run: mise settings experimental=true
      - run: ansible-galaxy collection install -r ansible/requirements.yml
      - run: mise r check
